# TODO (Avnishn): compute metrics in class
INTER_TOKEN_LAT = "inter_token_latency_s"
TTFT = "ttft_s"
E2E_LAT = "end_to_end_latency_s"
NUM_INPUT_TOKENS = "number_input_tokens"
NUM_OUTPUT_TOKENS = "number_output_tokens"
NUM_TOTAL_TOKENS = "number_total_tokens"
REQ_OUTPUT_THROUGHPUT = "request_output_throughput_token_per_s"
ERROR_MSG = "error_msg"
ERROR_CODE = "error_code"
ERROR_CODE_FREQ = "error_code_frequency"
NUM_ERRORS = "number_errors"
OUTPUT_THROUGHPUT = "mean_output_throughput_token_per_s"
NUM_COMPLETED_REQUESTS = "num_completed_requests"
COMPLETED_REQUESTS_PER_MIN = "num_completed_requests_per_min"
ERROR_RATE = "error_rate"
NUM_REQ_STARTED = "num_requests_started"
